// 1) Regenerates global.css (CSS variables for light + dark) from constants/tokens.cjs.
// 2) Verifies constants/tokens.ts carries the same palette and radius, so useColors() and Tailwind never disagree.
// Run: npm run tokens:sync  (also runs before typecheck)
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const here = (p) => fileURLToPath(new URL(p, import.meta.url));
const { palette, radius } = require(here('../constants/tokens.cjs'));

const kebab = (s) => s.replace(/([A-Z])/g, '-$1').toLowerCase();
const rgb = (hex) => hex.replace('#', '').match(/.{2}/g).map((h) => parseInt(h, 16)).join(' ');
const vars = (theme) => Object.entries(palette[theme]).map(([k, v]) => `    --color-${kebab(k)}: ${rgb(v)};`).join('\n');

const css = `@tailwind base;
@tailwind components;
@tailwind utilities;

/* GENERATED by scripts/tokens-sync.mjs from constants/tokens.cjs. Do not edit by hand. */
@layer base {
  :root {
${vars('light')}
  }
  @media (prefers-color-scheme: dark) {
    :root {
${vars('dark')}
    }
  }
}
`;
writeFileSync(here('../global.css'), css);

const ts = readFileSync(here('../constants/tokens.ts'), 'utf8');
let bad = 0;
for (const theme of ['light', 'dark']) {
  const start = ts.indexOf(`${theme}: {`);
  const block = ts.slice(start, ts.indexOf('},', start));
  for (const [k, v] of Object.entries(palette[theme])) {
    if (!new RegExp(`\\b${k}:\\s*'${v}'`).test(block)) { console.error(`tokens.ts drift: ${theme}.${k} should be ${v}`); bad++; }
  }
}
const rStart = ts.indexOf('radius = {');
const rBlock = ts.slice(rStart, ts.indexOf('}', rStart));
for (const [k, v] of Object.entries(radius)) {
  if (!new RegExp(`\\b${k}:\\s*${v}\\b`).test(rBlock)) { console.error(`tokens.ts drift: radius.${k} should be ${v}`); bad++; }
}
if (bad) process.exit(1);
console.log('global.css regenerated; tokens.ts matches tokens.cjs');
